# resolution: 0.25
frame_id: /map # Static global frame
resolution: 0.25 # Resolution in meter
base_frame_id: /base_footprint # The robot's base frame (for ground plane detection)
height_map: false  # Whether visualization should encode height with different colors

color: # Color for visualizing occupied cells when ~heigh_map=False, in range [0:1]
    r: 0
    g: 1.0
    b: 0
    a: 0.4

sensor_model:
    max_range: 12 # Maximum range in meter (Y) for inserting point cloud data when dynamically building a map
    hit: 1.0 #0.7 # Probabilities for hits in the sensor model when dynamically building a map
    miss: 0.0 #0.4 # Probabilities for missings in the sensor model when dynamically building a map
    min: 0.12 # Minimum probability for clamping when dynamically building a map
    max: 0.97 # Maximum probability for clamping when dynamically building a map

latch: false # Whether topics are published latched or only once per change. For maximum performance when building a map set to false.
filter_ground: false # Whether the ground plane should be detected and ignored from scan data when dynamically building a map

ground_filter:
    distance: 0.1 # Distance threshold for points (in z direction) to be segmented to the ground plane
    angle: 0.15 # Angular threshold of the detected plane from the horizontal plane to be detected as ground
    plane_distance: 0.1 # Distance threshold from z=0 for a plane to be detected as ground
    
# pointcloud_min_z: -0.5 # Minimum height of points to consider for insertion in the callback.
# pointcloud_max_z: 3.5 # Maximum height of points to consider for insertion in the callback.
# occupancy_min_z: -0.5 # Minimum height of occupied cells to be consider in the final map.
# occupancy_min_z: 3.5 # Maximum height of occupied cells to be consider in the final map.